[build]
  command = "npm run build"
  # Remove publish directory to let Netlify auto-detect Next.js

[build.environment]
  NODE_VERSION = "18"  # Adjust to your preferred Node.js version
  NETLIFY_DISABLE_SECRETS_DETECTION = "true"  # Explicitly disable secrets scanning
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"  # Additional secrets scanning disable
  NETLIFY_SKIP_SECRETS_SCAN = "true"  # Force skip secrets scan

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
