[build]
  command = "npm run build"
  # Remove publish directory to let Netlify auto-detect Next.js

[build.environment]
  NODE_VERSION = "18"  # Adjust to your preferred Node.js version
  NETLIFY_DISABLE_SECRETS_DETECTION = "true"  # Explicitly disable secrets scanning
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"  # Additional secrets scanning disable
  NETLIFY_SKIP_SECRETS_SCAN = "true"  # Force skip secrets scan

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Wildcard domain configuration for subdomains
[[redirects]]
  from = "https://mahikeng.smartkollect.co.za/*"
  to = "https://smartkollect.co.za/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "mahikeng.smartkollect.co.za"}

[[redirects]]
  from = "https://triplem.smartkollect.co.za/*"
  to = "https://smartkollect.co.za/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "triplem.smartkollect.co.za"}

[[redirects]]
  from = "https://univen.smartkollect.co.za/*"
  to = "https://smartkollect.co.za/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "univen.smartkollect.co.za"}

# Handle www redirects for subdomains
[[redirects]]
  from = "https://www.mahikeng.smartkollect.co.za/*"
  to = "https://mahikeng.smartkollect.co.za/:splat"
  status = 301

[[redirects]]
  from = "https://www.triplem.smartkollect.co.za/*"
  to = "https://triplem.smartkollect.co.za/:splat"
  status = 301

[[redirects]]
  from = "https://www.univen.smartkollect.co.za/*"
  to = "https://univen.smartkollect.co.za/:splat"
  status = 301
