[build]
  publish = "dist"  # Adjust this to your build output directory if needed

[build.environment]
  NODE_VERSION = "18"  # Adjust to your preferred Node.js version

# Disable secrets scanning
[plugins."@netlify/plugin-secrets"]
  enabled = false

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
